<%@ Language="VBScript" CodePage=65001 %>
<% Option Explicit %>
<!-- #include file="includes/data.inc" -->
<!-- #include file="includes/layout.inc" -->
<script language="JScript" runat="server">
function reportRuntimeLabel() {
    return "server-side JScript helper";
}
</script>
<%
Dim customers
customers = BuildCustomerFixtures()

Dim metrics
Set metrics = BuildMetrics(customers)

Function RenderReportRows(ByVal customerList)
    Dim html
    html = ""

    Dim index
    For index = 0 To UBound(customerList)
        html = html & _
            "<tr>" & _
                "<td>" & Server.HTMLEncode(customerList(index).Id) & "</td>" & _
                "<td>" & Server.HTMLEncode(customerList(index).Name) & "</td>" & _
                "<td>" & Server.HTMLEncode(customerList(index).TierLabel) & "</td>" & _
                "<td>" & Server.HTMLEncode(FormatCurrencyValue(customerList(index).Balance)) & "</td>" & _
                "<td>" & Server.HTMLEncode(customerList(index).StatusText) & "</td>" & _
            "</tr>"
    Next

    RenderReportRows = html
End Function

Function RenderMetricSummary(ByVal metricMap)
    RenderMetricSummary = _
        "<ul class=""summary-list"">" & _
            "<li><strong>" & Server.HTMLEncode(CStr(metricMap("active"))) & "</strong><span>active</span></li>" & _
            "<li><strong>" & Server.HTMLEncode(CStr(metricMap("premium"))) & "</strong><span>premium</span></li>" & _
            "<li><strong>" & Server.HTMLEncode(CStr(metricMap("overdue"))) & "</strong><span>overdue</span></li>" & _
            "<li><strong>" & Server.HTMLEncode(FormatCurrencyValue(metricMap("balance"))) & "</strong><span>balance</span></li>" & _
        "</ul>"
End Function
%>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reports - Classic ASP Sample</title>
    <style>
        body {
            margin: 0;
            font-family: "Inter", "Segoe UI", sans-serif;
            background: #f5f7f8;
            color: #1d2733;
        }

        header {
            display: grid;
            gap: 16px;
            padding: 28px 32px;
            border-bottom: 1px solid #ccd5d8;
            background: #fff;
        }

        .sample-nav {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
        }

        .sample-nav a {
            padding: 8px 10px;
            border-radius: 6px;
            color: #1d2733;
            text-decoration: none;
        }

        .sample-nav a[aria-current="page"] {
            background: #e5eff4;
            color: #2f5f9f;
            font-weight: 700;
        }

        main {
            display: grid;
            gap: 18px;
            padding: 30px;
        }

        .summary-list {
            display: grid;
            grid-template-columns: repeat(4, minmax(120px, 1fr));
            gap: 12px;
            margin: 0;
            padding: 0;
            list-style: none;
        }

        .summary-list li {
            display: grid;
            gap: 6px;
            padding: 16px;
            border: 1px solid #ccd5d8;
            border-radius: 8px;
            background: #fff;
        }

        .summary-list strong {
            font-size: 1.35rem;
        }

        .report-table {
            overflow: auto;
            border: 1px solid #ccd5d8;
            border-radius: 8px;
            background: #fff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 12px 14px;
            border-bottom: 1px solid #ccd5d8;
            text-align: left;
        }

        th {
            color: #68727f;
            font-size: 0.82rem;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <header>
        <div>
            <h1>Reports</h1>
            <p>Generated by <%= Server.HTMLEncode(reportRuntimeLabel()) %>.</p>
        </div>
        <%= RenderSampleNavigation("reports") %>
    </header>

    <main>
        <section aria-label="Report summary">
            <%= RenderMetricSummary(metrics) %>
        </section>

        <section class="report-table" aria-label="Customer report">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Tier</th>
                        <th>Balance</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <%= RenderReportRows(customers) %>
                </tbody>
            </table>
        </section>
    </main>
</body>
</html>
